import { Building } from './types';

export const BUILDINGS: Building[] = [
  // --- ДРЕВНИЙ МИР (1-15) ---
  { 
    id: 'gobekli', 
    name: 'Гёбекли-Тепе', 
    location: 'Турция', 
    countryCode: 'tr',
    height: 6, 
    yearBuilt: -10000, 
    yearDestroyed: -8000, 
    activeUntil: -8000, 
    category: 'Ancient', 
    description: 'Древнейший храмовый комплекс человечества.', 
    funFact: 'На 6000 лет старше Стоунхенджа.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/G%C3%B6bekli_Tepe%2C_Urfa.jpg/800px-G%C3%B6bekli_Tepe%2C_Urfa.jpg',
    isFormerRecordHolder: true
  },
  { 
    id: 'jericho', 
    name: 'Башня Иерихона', 
    location: 'Палестина', 
    countryCode: 'ps',
    height: 8.5, 
    yearBuilt: -8000, 
    yearDestroyed: -5000, 
    activeUntil: -5000, 
    category: 'Ancient', 
    description: 'Первое высотное сооружение неолита.', 
    funFact: 'Имела внутреннюю лестницу из 22 ступеней.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Ziko.jpg/500px-Ziko.jpg',
    isFormerRecordHolder: true
  },
  { 
    id: 'menhir', 
    name: 'Менгир Эр-Грах', 
    location: 'Франция', 
    countryCode: 'fr',
    height: 20.7, 
    yearBuilt: -5000, 
    yearDestroyed: -4000, 
    activeUntil: -4000, 
    category: 'Ancient', 
    description: 'Крупнейший одиночный мегалит Европы.', 
    funFact: 'Упал и раскололся на 4 части около 4000 г. до н.э.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Er_Grah_menhir.jpg',
    isFormerRecordHolder: true
  },
  { 
    id: 'anu-ziggurat', 
    name: 'Зиккурат Ану (Урук)', 
    location: 'Ирак', 
    countryCode: 'iq',
    height: 13, 
    yearBuilt: -4000, 
    yearDestroyed: -3600, 
    activeUntil: -3600, 
    category: 'Ancient', 
    description: 'Ранний шумерский зиккурат.', 
    funFact: 'Служил основанием для легендарного "Белого храма".', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Uruk_White_Temple_Rendering.png/500px-Uruk_White_Temple_Rendering.png',
    isFormerRecordHolder: true
  },
  { 
    id: 'newgrange', 
    name: 'Ньюгрейндж', 
    location: 'Ирландия', 
    countryCode: 'ie',
    height: 13.5, 
    yearBuilt: -3600, 
    activeUntil: 2100, 
    category: 'Ancient', 
    description: 'Мегалитическое сооружение, старше пирамид.', 
    funFact: 'Вход освещается солнцем только в день зимнего солнцестояния.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Irelands_history.jpg/500px-Irelands_history.jpg',
    isFormerRecordHolder: true
  },
  { 
    id: 'caral', 
    name: 'Пирамида Караля', 
    location: 'Перу', 
    countryCode: 'pe',
    height: 26, 
    yearBuilt: -3000, 
    activeUntil: -2750, 
    category: 'Ancient', 
    description: 'Древнейшая пирамида Южной Америки.', 
    funFact: 'Центр священного города цивилизации Норте-Чико.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/The_pyramids_of_Caral_in_Peru.jpg/800px-The_pyramids_of_Caral_in_Peru.jpg',
    isFormerRecordHolder: true
  },
  { 
    id: 'silbury', 
    name: 'Силбери-Хилл', 
    location: 'Великобритания', 
    countryCode: 'gb',
    height: 40, 
    yearBuilt: -2750, 
    activeUntil: -2650, 
    category: 'Ancient', 
    description: 'Самый высокий доисторический курган Европы.', 
    funFact: 'Его объем составляет около 248 тысяч кубических метров.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Silbury_Hill%2C_England.jpg',
    isFormerRecordHolder: true
  },
  { 
    id: 'djoser', 
    name: 'Пирамида Джосера', 
    location: 'Египет', 
    countryCode: 'eg',
    height: 62.5, 
    yearBuilt: -2650, 
    activeUntil: 2100, 
    category: 'Ancient', 
    description: 'Первая пирамида в Саккаре.', 
    funFact: 'Архитектор Имхотеп первым сложил мастабы друг на друга.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Saqqara_BW_5.jpg/500px-Saqqara_BW_5.jpg',
    isFormerRecordHolder: true
  },
  { 
    id: 'meidum', 
    name: 'Пирамида в Мейдуме', 
    location: 'Египет', 
    countryCode: 'eg',
    height: 93.5, 
    yearBuilt: -2620, 
    yearDestroyed: -100, 
    activeUntil: 0, 
    category: 'Ancient', 
    description: 'Вторая пирамида Снофру, обрушилась в древности.', 
    funFact: 'Сейчас её высота составляет всего 65 метров.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/02_meidum_pyramid.jpg/500px-02_meidum_pyramid.jpg',
    isFormerRecordHolder: true
  },
  { 
    id: 'bent', 
    name: 'Ломаная пирамида', 
    location: 'Египет', 
    countryCode: 'eg',
    height: 104.7, 
    yearBuilt: -2605, 
    activeUntil: 2100, 
    category: 'Ancient', 
    description: 'Пирамида с уникальным углом наклона.', 
    funFact: 'Её грани резко меняют угол на середине высоты.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/92/02_bent_north_entrance.jpg',
    isFormerRecordHolder: true
  },
  { 
    id: 'red', 
    name: 'Розовая пирамида', 
    location: 'Египет', 
    countryCode: 'eg',
    height: 109.5, 
    yearBuilt: -2600, 
    activeUntil: 2100, 
    category: 'Ancient', 
    description: 'Первая успешная правильная гладкая пирамида.', 
    funFact: 'Цвет камня становится розовым в лучах заката.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Egypt.Dashur.RedPyramid.01.jpg',
    isFormerRecordHolder: true
  },
  { 
    id: 'khufu', 
    name: 'Пирамида Хеопса', 
    location: 'Египет', 
    countryCode: 'eg',
    height: 146.6, 
    yearBuilt: -2570, 
    activeUntil: 2100, 
    category: 'Ancient', 
    description: 'Величайшее достижение древнего мира. Рекорд на 3800 лет.', 
    funFact: 'Из-за эрозии её высота сейчас около 138 метров.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Kheops-Pyramid.jpg/800px-Kheops-Pyramid.jpg',
    isFormerRecordHolder: true
  },
  { 
    id: 'khafre', 
    name: 'Пирамида Хафры', 
    location: 'Египет', 
    countryCode: 'eg',
    height: 143.5, 
    yearBuilt: -2550, 
    activeUntil: 2100, 
    category: 'Ancient', 
    description: 'Вторая по величине пирамида в Гизе.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Egypt.Giza.Sphinx.01.jpg',
    funFact: 'На её вершине сохранилась часть оригинальной облицовки.'
  },
  { 
    id: 'etemenanki', 
    name: 'Этеменанки (Вавилон)', 
    location: 'Ирак', 
    countryCode: 'iq',
    height: 91, 
    yearBuilt: -600, 
    yearDestroyed: -323, 
    activeUntil: -323, 
    category: 'Ancient', 
    description: 'Зиккурат Мардука, прообраз Вавилонской башни.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Etemenanki_Berlin.jpg',
    funFact: 'Разрушен во время похода Александра Македонского.'
  },
  { 
    id: 'pharos', 
    name: 'Александрийский маяк', 
    location: 'Египет', 
    countryCode: 'eg',
    height: 110, 
    yearBuilt: -280, 
    yearDestroyed: 1303, 
    activeUntil: 1303, 
    category: 'Engineering', 
    description: 'Седьмое чудо света на острове Фарос.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Lighthouse_-_Thiersch.png/500px-Lighthouse_-_Thiersch.png',
    funFact: 'Был изображен на многих монетах того времени.'
  },

  // --- СРЕДНЕВЕКОВЬЕ И ПЕРЕХОДНЫЙ ПЕРИОД (16-30) ---
  { 
    id: 'kanishka', 
    name: 'Ступа Канишки', 
    location: 'Пакистан', 
    countryCode: 'pk',
    height: 122, 
    yearBuilt: 151, 
    yearDestroyed: 600, 
    activeUntil: 600, 
    category: 'Ancient', 
    description: 'Высочайшая буддийская ступа древности.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Loriyan_Tangai_complete_Stupa.jpg/500px-Loriyan_Tangai_complete_Stupa.jpg',
    funFact: 'Её описывали как "высочайшее здание мира" китайские паломники.'
  },
  { 
    id: 'jetavanaramaya', 
    name: 'Джетаванарама', 
    location: 'Шри-Ланка', 
    countryCode: 'lk',
    height: 122, 
    yearBuilt: 273, 
    activeUntil: 2100, 
    category: 'Ancient', 
    description: 'Крупнейшее кирпичное здание древнего мира.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Jetavanaramaya_Stupa_profile.jpg/1280px-Jetavanaramaya_Stupa_profile.jpg',
    funFact: 'При строительстве использовали 93 миллиона кирпичей.'
  },
  { 
    id: 'yongning', 
    name: 'Пагода Юннин', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 147, 
    yearBuilt: 516, 
    yearDestroyed: 534, 
    activeUntil: 534, 
    category: 'Engineering', 
    description: 'Деревянная пагода Лояна.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3c/20251018_Model_of_Yongning_Temple_Pagoda.jpg',
    funFact: 'Сгорела всего через 18 лет после завершения.'
  },
  { 
    id: 'hagia-sophia', 
    name: 'Собор Св. Софии', 
    location: 'Турция', 
    countryCode: 'tr',
    height: 56, 
    yearBuilt: 537, 
    activeUntil: 2100, 
    category: 'Gothic', 
    description: 'Символ Византии в Константинополе.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Hagia_Sophia_Mars_2013.jpg/800px-Hagia_Sophia_Mars_2013.jpg',
    funFact: 'Его купол кажется парящим в воздухе.'
  },
  { 
    id: 'lincoln', 
    name: 'Линкольнский собор', 
    location: 'Великобритания', 
    countryCode: 'gb',
    height: 159.7, 
    yearBuilt: 1311, 
    yearDestroyed: 1549, 
    activeUntil: 1549, 
    category: 'Gothic', 
    description: 'Первое здание, обошедшее пирамиду Хеопса.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Lincoln_Cathedral_viewed_from_Lincoln_Castle.jpg/800px-Lincoln_Cathedral_viewed_from_Lincoln_Castle.jpg',
    isFormerRecordHolder: true,
    funFact: 'Шпиль обрушился во время бури в 1549 году.'
  },
  { 
    id: 'oleviste', 
    name: 'Церковь Св. Олафа', 
    location: 'Эстония', 
    countryCode: 'ee',
    height: 158.4, 
    yearBuilt: 1549, 
    yearDestroyed: 1625, 
    activeUntil: 1625, 
    category: 'Gothic', 
    description: 'Символ Таллина и Ганзейского союза.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/St._Olaf%27s_church%2C_Tallinn.jpg/500px-St._Olaf%27s_church%2C_Tallinn.jpg',
    isFormerRecordHolder: true,
    funFact: 'В её шпиль молния ударяла не менее 10 раз.'
  },
  { 
    id: 'beauvais', 
    name: 'Собор Сен-Пьер-де-Бове', 
    location: 'Франция', 
    countryCode: 'fr',
    height: 153, 
    yearBuilt: 1569, 
    yearDestroyed: 1573, 
    activeUntil: 1573, 
    category: 'Gothic', 
    description: 'Амбициозный готический проект.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Beauvais_-_Cath%C3%A9drale_Saint-Pierre_-_Ext%C3%A9rieur_02.jpg/500px-Beauvais_-_Cath%C3%A9drale_Saint-Pierre_-_Ext%C3%A9rieur_02.jpg',
    isFormerRecordHolder: true,
    funFact: 'Шпиль рухнул через 4 года после постройки.'
  },
  { 
    id: 'st-mary-stralsund', 
    name: 'Церковь Св. Марии', 
    location: 'Германия', 
    countryCode: 'de',
    height: 151, 
    yearBuilt: 1625, 
    yearDestroyed: 1647, 
    activeUntil: 1647, 
    category: 'Gothic', 
    description: 'Высочайшее здание мира в середине XVII века.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/St_Mary%27s_Church_Stralsund_Interior.jpg/500px-St_Mary%27s_Church_Stralsund_Interior.jpg',
    isFormerRecordHolder: true,
    funFact: 'Шпиль сгорел от молнии в 1647 году.'
  },
  { 
    id: 'strasbourg', 
    name: 'Страсбургский собор', 
    location: 'Франция', 
    countryCode: 'fr',
    height: 142, 
    yearBuilt: 1647, 
    activeUntil: 2100, 
    category: 'Gothic', 
    description: 'Удерживал рекорд высоты 227 лет.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Strasbourg_Cathedral_Exterior_-_Diliff.jpg/500px-Strasbourg_Cathedral_Exterior_-_Diliff.jpg',
    isFormerRecordHolder: true,
    funFact: 'Выполнен из розового песчаника.'
  },
  { 
    id: 'st-paul-london', 
    name: 'Собор Святого Павла', 
    location: 'Великобритания', 
    countryCode: 'gb',
    height: 111, 
    yearBuilt: 1710, 
    activeUntil: 2100, 
    category: 'Gothic', 
    description: 'Шедевр Кристофера Рена в Лондоне.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/St_Pauls_aerial_%28cropped%29.jpg/1280px-St_Pauls_aerial_%28cropped%29.jpg',
    funFact: 'Был высочайшим зданием Лондона 250 лет.'
  },
  { 
    id: 'st-nikolai', 
    name: 'Собор Св. Николая', 
    location: 'Германия', 
    countryCode: 'de',
    height: 147.3, 
    yearBuilt: 1874, 
    activeUntil: 1943, 
    category: 'Gothic', 
    description: 'Высочайший собор своего времени в Гамбурге.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Nikolaikirche_Hamburg_von_Nikolaibruecke.jpg/494px-Nikolaikirche_Hamburg_von_Nikolaibruecke.jpg',
    isFormerRecordHolder: true,
    funFact: 'Разрушен во время Второй мировой войны.'
  },
  { 
    id: 'rouen', 
    name: 'Руанский собор', 
    location: 'Франция', 
    countryCode: 'fr',
    height: 151, 
    yearBuilt: 1876, 
    activeUntil: 2100, 
    category: 'Gothic', 
    description: 'Лидер Франции до появления Эйфелевой башни.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Cathedrale_de_Rouen_1.jpg/500px-Cathedrale_de_Rouen_1.jpg',
    isFormerRecordHolder: true,
    funFact: 'Имеет чугунный шпиль.'
  },
  { 
    id: 'cologne', 
    name: 'Кёльнский собор', 
    location: 'Германия', 
    countryCode: 'de',
    height: 157.4, 
    yearBuilt: 1880, 
    activeUntil: 2100, 
    category: 'Gothic', 
    description: 'Строился более 600 лет.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Koelner_Dom_Night.jpg/500px-Koelner_Dom_Night.jpg',
    isFormerRecordHolder: true,
    funFact: 'Шпили закончены только в XIX веке.'
  },
  { 
    id: 'washington', 
    name: 'Монумент Вашингтона', 
    location: 'США', 
    countryCode: 'us',
    height: 169.3, 
    yearBuilt: 1884, 
    activeUntil: 2100, 
    category: 'Engineering', 
    description: 'Каменный обелиск в Вашингтоне.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Washington_Monument_Dusk_Jan_2006.jpg/800px-Washington_Monument_Dusk_Jan_2006.jpg',
    isFormerRecordHolder: true,
    funFact: 'Самое высокое каменное сооружение в мире.'
  },
  { 
    id: 'liberty-statue', 
    name: 'Статуя Свободы', 
    location: 'США', 
    countryCode: 'us',
    height: 93, 
    yearBuilt: 1886, 
    activeUntil: 2100, 
    category: 'Statue', 
    description: 'Подарок Франции народу США.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Statue_of_Liberty_7.jpg/500px-Statue_of_Liberty_7.jpg',
    funFact: 'Её лицо было смоделировано по образу матери скульптора.'
  },

  // --- ЭПОХА СТАЛИ И НЕБОСКРЕБОВ (31-60) ---
  { 
    id: 'eiffel', 
    name: 'Эйфелева башня', 
    location: 'Франция', 
    countryCode: 'fr',
    height: 312, 
    yearBuilt: 1889, 
    activeUntil: 2100, 
    category: 'Engineering', 
    description: 'Символ Парижа, триумф стали.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg/800px-Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg',
    isFormerRecordHolder: true,
    funFact: 'Летом она становится выше на 15 см.'
  },
  { 
    id: 'chrysler', 
    name: 'Крайслер-билдинг', 
    location: 'США', 
    countryCode: 'us',
    height: 319, 
    yearBuilt: 1930, 
    activeUntil: 2100, 
    category: 'Industrial', 
    description: 'Шедевр Ар-деко в Нью-Йорке.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Chrysler_Building_by_David_Shankbone_Retouched.jpg/800px-Chrysler_Building_by_David_Shankbone_Retouched.jpg',
    isFormerRecordHolder: true,
    funFact: 'Шпиль собрали тайно внутри башни.'
  },
  { 
    id: 'empire', 
    name: 'Эмпайр-стейт-билдинг', 
    location: 'США', 
    countryCode: 'us',
    height: 443.2, 
    yearBuilt: 1931, 
    activeUntil: 2100, 
    category: 'Industrial', 
    description: 'Легендарный небоскреб Нью-Йорка.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Empire_State_Building_%28aerial_view%29.jpg/500px-Empire_State_Building_%28aerial_view%29.jpg',
    isFormerRecordHolder: true,
    funFact: 'Был самым высоким зданием мира 40 лет.'
  },
  { 
    id: 'boganida', 
    name: 'Боганидская радиомачта', 
    location: 'Россия', 
    countryCode: 'ru',
    height: 462, 
    yearBuilt: 1960, 
    activeUntil: 2100, 
    category: 'Mast', 
    description: 'Сверхвысокая мачта в Арктике.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg',
    funFact: 'Служит для навигации в северных морях.'
  },
  { 
    id: 'kvly-mast', 
    name: 'Телерадиомачта KVLY-TV', 
    location: 'США', 
    countryCode: 'us',
    height: 628.8, 
    yearBuilt: 1963, 
    activeUntil: 2100, 
    category: 'Mast', 
    description: 'Высочайшая мачта США.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/KVLY_TV_Mast_North_Dakota.jpg/500px-KVLY_TV_Mast_North_Dakota.jpg',
    funFact: 'Была высочайшим сооружением мира до 2008 года.'
  },
  { 
    id: 'gateway-arch', 
    name: 'Арка в Сент-Луисе', 
    location: 'США', 
    countryCode: 'us',
    height: 192, 
    yearBuilt: 1965, 
    activeUntil: 2100, 
    category: 'Engineering', 
    description: 'Символ "Врат на Запад".', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Gateway_Arch_Under_Blue_Sky.jpg/500px-Gateway_Arch_Under_Blue_Sky.jpg',
    funFact: 'Ширина арки равна её высоте.'
  },
  { 
    id: 'ostankino', 
    name: 'Останкинская телебашня', 
    location: 'Россия', 
    countryCode: 'ru',
    height: 540, 
    yearBuilt: 1967, 
    activeUntil: 2100, 
    category: 'Engineering', 
    description: 'Самое высокое сооружение Европы.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Ostankino_Tower_2017.jpg/500px-Ostankino_Tower_2017.jpg',
    isFormerRecordHolder: true,
    funFact: 'Имеет вращающийся ресторан "Седьмое небо".'
  },
  { 
    id: 'motherland', 
    name: 'Родина-мать зовет!', 
    location: 'Россия', 
    countryCode: 'ru',
    height: 85, 
    yearBuilt: 1967, 
    activeUntil: 2100, 
    category: 'Statue', 
    description: 'Высочайшая статуя России в Волгограде.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/ru/thumb/f/f8/%D0%A0%D0%BE%D0%B4%D0%B8%D0%BD%D0%B0-%D0%BC%D0%B0%D1%82%D1%8C_%D0%B7%D0%BE%D0%B2%D0%B5%D1%82%21.JPG/500px-%D0%A0%D0%BE%D0%B4%D0%B8%D0%BD%D0%B0-%D0%BC%D0%B0%D1%82%D1%8C_%D0%B7%D0%BE%D0%B2%D0%B5%D1%82%21.JPG',
    funFact: 'Вес меча составляет 14 тонн.'
  },
  { 
    id: 'hancock-center', 
    name: '875 Норт-Мичиган-авеню', 
    location: 'США', 
    countryCode: 'us',
    height: 456.9, 
    yearBuilt: 1969, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Чикагский гигант с экзоскелетом.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/John_Hancock_Center.jpg/500px-John_Hancock_Center.jpg',
    funFact: 'Первое в мире здание с перекрестными связями.'
  },
  { 
    id: 'warsaw-mast', 
    name: 'Варшавская радиомачта', 
    location: 'Польша', 
    countryCode: 'pl',
    height: 646.4, 
    yearBuilt: 1974, 
    yearDestroyed: 1991, 
    activeUntil: 1991, 
    category: 'Mast', 
    description: 'Самое высокое сооружение в истории до 2008 года.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Warsaw_Radio_Mast_Gabin.jpg/500px-Warsaw_Radio_Mast_Gabin.jpg',
    isFormerRecordHolder: true,
    funFact: 'Обрушилась во время ремонта в 1991 году.'
  },
  { 
    id: 'willis', 
    name: 'Уиллис-тауэр', 
    location: 'США', 
    countryCode: 'us',
    height: 527, 
    yearBuilt: 1974, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Бывший Сирс-Тауэр в Чикаго.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Willis_Tower_From_Lake.jpg/500px-Willis_Tower_From_Lake.jpg',
    isFormerRecordHolder: true,
    funFact: 'В ясный день видно территорию 4 штатов.'
  },
  { 
    id: 'cn-tower', 
    name: 'Си-Эн Тауэр', 
    location: 'Канада', 
    countryCode: 'ca',
    height: 553.3, 
    yearBuilt: 1976, 
    activeUntil: 2100, 
    category: 'Engineering', 
    description: 'Символ Торонто и Канады.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/CN_Tower_from_Lake_2002.jpg/469px-CN_Tower_from_Lake_2002.jpg',
    isFormerRecordHolder: true,
    funFact: 'Была высочайшим сооружением мира 30 лет.'
  },
  { 
    id: 'rjh63', 
    name: 'Радиомачта RJH63', 
    location: 'Россия', 
    countryCode: 'ru',
    height: 424.9, 
    yearBuilt: 1979, 
    activeUntil: 2100, 
    category: 'Mast', 
    description: 'Мачта системы связи ВМФ.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg',
    funFact: 'Находится в Имеретинской станице.'
  },
  { 
    id: 'tianjin-tv-tower', 
    name: 'Тяньцзиньская телебашня', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 415.1, 
    yearBuilt: 1981, 
    activeUntil: 2100, 
    category: 'Engineering', 
    description: 'Башня на искусственном озере.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Tianjin_Radio_and_Television_Tower.jpg/500px-Tianjin_Radio_and_Television_Tower.jpg',
    funFact: 'Единственная в мире башня на воде.'
  },
  { 
    id: 'ekibastuz', 
    name: 'Труба Экибастузской ГРЭС-2', 
    location: 'Казахстан', 
    countryCode: 'kz',
    height: 419.7, 
    yearBuilt: 1987, 
    activeUntil: 2100, 
    category: 'Industrial', 
    description: 'Самая высокая дымовая труба в мире.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Ekibastuz_GRES-2_chimney.jpg/500px-Ekibastuz_GRES-2_chimney.jpg',
    funFact: 'Выше Эмпайр-стейт-билдинга.'
  },

  // --- СОВРЕМЕННЫЙ ПИК (61-100) ---
  { 
    id: 'beijing-tv', 
    name: 'Пекинская телебашня', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 410.5, 
    yearBuilt: 1992, 
    activeUntil: 2100, 
    category: 'Engineering', 
    description: 'Высочайшее сооружение Пекина 90-х.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Beijing_CCTV_Tower.jpg/500px-Beijing_CCTV_Tower.jpg',
    funFact: 'Имеет самую большую открытую площадку в мире.'
  },
  { 
    id: 'central-plaza', 
    name: 'Сентрал-Плаза', 
    location: 'Гонконг', 
    countryCode: 'hk',
    height: 374, 
    yearBuilt: 1992, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Треугольный небоскреб Гонконга.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Central_Plaza_Hong_Kong.jpg/500px-Central_Plaza_Hong_Kong.jpg',
    funFact: 'На вершине находится самая высокая церковь в мире.'
  },
  { 
    id: 'ushiku-daibutsu', 
    name: 'Усику Дайбуцу', 
    location: 'Япония', 
    countryCode: 'jp',
    height: 100, 
    yearBuilt: 1993, 
    activeUntil: 2100, 
    category: 'Statue', 
    description: 'Огромная статуя Будды Амитабхи.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/6/62/Ushiku.jpg',
    funFact: 'Внутри есть смотровая площадка на уровне груди.'
  },
  { 
    id: 'oriental-pearl', 
    name: 'Восточная жемчужина', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 467.9, 
    yearBuilt: 1994, 
    activeUntil: 2100, 
    category: 'Engineering', 
    description: 'Символ Шанхая с 11 сферами.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Oriental_Pearl_Tower_Shanghai.jpg/500px-Oriental_Pearl_Tower_Shanghai.jpg',
    funFact: 'Её дизайн вдохновлен стихами династии Тан.'
  },
  { 
    id: 'kl-tower', 
    name: 'Менара Куала-Лумпур', 
    location: 'Малайзия', 
    countryCode: 'my',
    height: 420.4, 
    yearBuilt: 1996, 
    activeUntil: 2100, 
    category: 'Engineering', 
    description: 'Высочайшая башня Юго-Восточной Азии.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Menara_Kuala_Lumpur.jpg/500px-Menara_Kuala_Lumpur.jpg',
    funFact: 'Построена на холме с сохранением 100-летнего дерева.'
  },
  { 
    id: 'shun-hing', 
    name: 'Шунь Хин Сквер', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 384, 
    yearBuilt: 1996, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Первый стальной гигант Шэньчжэня.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Shun_Hing_Square_Shenzhen.jpg/500px-Shun_Hing_Square_Shenzhen.jpg',
    funFact: 'Строился со скоростью 4 этажа в 9 дней.'
  },
  { 
    id: 'petronas-1', 
    name: 'Башни Петронас', 
    location: 'Малайзия', 
    countryCode: 'my',
    height: 451.9, 
    yearBuilt: 1998, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Символ современной Малайзии.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Petronas_Panorama_II.jpg/500px-Petronas_Panorama_II.jpg',
    isFormerRecordHolder: true,
    funFact: 'Башни соединены двухэтажным мостом на 41-м этаже.'
  },
  { 
    id: 'krdk-mast', 
    name: 'Телерадиомачта KRDK-TV', 
    location: 'США', 
    countryCode: 'us',
    height: 627.8, 
    yearBuilt: 1998, 
    activeUntil: 2100, 
    category: 'Mast', 
    description: 'Одна из высочайших мачт Америки.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg',
    funFact: 'Находится в Северной Дакоте.'
  },
  { 
    id: 'jin-mao', 
    name: 'Башня Цзинь Мао', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 420.5, 
    yearBuilt: 1999, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Шанхайский небоскреб в форме пагоды.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Jin_Mao_Tower.jpg/500px-Jin_Mao_Tower.jpg',
    funFact: 'В дизайне часто повторяется число 8.'
  },
  { 
    id: 'kxtv-mast', 
    name: 'Телерадиомачта KXTV', 
    location: 'США', 
    countryCode: 'us',
    height: 624.5, 
    yearBuilt: 2000, 
    activeUntil: 2100, 
    category: 'Mast', 
    description: 'Лидер высоты в Калифорнии.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg',
    funFact: 'Расположена в Уолнат-Гров.'
  },
  { 
    id: 'ifc2', 
    name: 'Гонконгский МФЦ 2', 
    location: 'Гонконг', 
    countryCode: 'hk',
    height: 412, 
    yearBuilt: 2003, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Доминанта финансового района Гонконга.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Two_International_Finance_Centre.jpg/500px-Two_International_Finance_Centre.jpg',
    funFact: 'Появился в фильме "Темный рыцарь".'
  },
  { 
    id: 'taipei-101', 
    name: 'Тайбэй 101', 
    location: 'Тайвань', 
    countryCode: 'tw',
    height: 509.2, 
    yearBuilt: 2004, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Первое здание выше полукилометра.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Tower_of_Taipei_101%28cropped%29.jpg',
    isFormerRecordHolder: true,
    funFact: 'Имеет 660-тонный маятник для защиты от землетрясений.'
  },
  { 
    id: 'balashikha', 
    name: 'Балашихинская радиомачта', 
    location: 'Россия', 
    countryCode: 'ru',
    height: 427, 
    yearBuilt: 2004, 
    activeUntil: 2100, 
    category: 'Mast', 
    description: 'Главная мачта Подмосковья.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg',
    funFact: 'Обеспечивает связь на сотни километров.'
  },
  { 
    id: 'swfc', 
    name: 'Шанхайский ВМФЦ', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 494.3, 
    yearBuilt: 2008, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Здание-"открывашка" в Шанхае.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Shanghai_World_Financial_Center_2017.jpg/500px-Shanghai_World_Financial_Center_2017.jpg',
    funFact: 'Окно на вершине изначально планировалось круглым.'
  },
  { 
    id: 'spring-temple', 
    name: 'Будда Весеннего Храма', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 128, 
    yearBuilt: 2008, 
    activeUntil: 2100, 
    category: 'Statue', 
    description: 'Вторая по высоте статуя в мире.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Spring_Temple_Buddha_picturing_Vairocana%2C_in_Lushan_County%2C_Henan%2C_China.png/330px-Spring_Temple_Buddha_picturing_Vairocana%2C_in_Lushan_County%2C_Henan%2C_China.png',
    funFact: 'Статуя стоит на троне в виде лотоса.'
  },
  { 
    id: 'milad-tower', 
    name: 'Бордже Милад', 
    location: 'Иран', 
    countryCode: 'ir',
    height: 435, 
    yearBuilt: 2009, 
    activeUntil: 2100, 
    category: 'Engineering', 
    description: 'Высочайшее сооружение Ирана.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Milad_Tower_Tehran.jpg/500px-Milad_Tower_Tehran.jpg',
    funFact: 'Гондола башни является самой большой в мире.'
  },
  { 
    id: 'trump-chicago', 
    name: 'Отель Трампа', 
    location: 'США', 
    countryCode: 'us',
    height: 423.2, 
    yearBuilt: 2009, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Зеркальный гигант Чикаго.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Trump_International_Hotel_and_Tower_Chicago.jpg/500px-Trump_International_Hotel_and_Tower_Chicago.jpg',
    funFact: 'Отражает небо и реку Чикаго.'
  },
  { 
    id: 'burj-khalifa', 
    name: 'Бурдж-Халифа', 
    location: 'ОАЭ', 
    countryCode: 'ae',
    height: 829.8, 
    yearBuilt: 2010, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Самое высокое здание в истории.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/ru/thumb/2/2f/Burj_Khalifa_building.jpg/960px-Burj_Khalifa_building.jpg',
    isFormerRecordHolder: true,
    funFact: 'Имеет 163 этажа.'
  },
  { 
    id: 'guangzhou-tv', 
    name: 'Телебашня Гуанчжоу', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 604, 
    yearBuilt: 2010, 
    activeUntil: 2100, 
    category: 'Engineering', 
    description: 'Башня с гиперболоидной конструкцией.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Canton_Tower_at_Night.jpg/500px-Canton_Tower_at_Night.jpg',
    funFact: 'Её силуэт называют "тонкой талией".'
  },
  { 
    id: 'icc-hk', 
    name: 'МКЦ Гонконг', 
    location: 'Гонконг', 
    countryCode: 'hk',
    height: 484, 
    yearBuilt: 2010, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Самое высокое здание Гонконга.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/ICC_Tower_Hong_Kong.jpg/500px-ICC_Tower_Hong_Kong.jpg',
    funFact: 'На вершине расположен отель Ritz-Carlton.'
  },
  { 
    id: 'zifeng-tower', 
    name: 'Башня Цзыфэн', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 450, 
    yearBuilt: 2010, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Ступенчатый гигант Нанкина.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Zifeng_Tower.jpg/500px-Zifeng_Tower.jpg',
    funFact: 'Включает офисы, отель и обсерваторию.'
  },
  { 
    id: 'guangzhou-ifc', 
    name: 'Гуанчжоуский МФЦ', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 438.6, 
    yearBuilt: 2010, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Западная башня Гуанчжоу.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Guangzhou_IFC.jpg/500px-Guangzhou_IFC.jpg',
    funFact: 'Имеет обтекаемую форму для снижения ветра.'
  },
  { 
    id: 'al-hamra', 
    name: 'Башня Аль-Хамра', 
    location: 'Кувейт', 
    countryCode: 'kw',
    height: 412.6, 
    yearBuilt: 2011, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Скрученное бетонное здание.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Al_Hamra_Tower_Kuwait.jpg/500px-Al_Hamra_Tower_Kuwait.jpg',
    funFact: 'Самое высокое здание Кувейта.'
  },
  { 
    id: 'kk100', 
    name: 'Kingkey 100', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 441.8, 
    yearBuilt: 2011, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Небоскреб с дугообразным силуэтом.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/KK100_Shenzhen.jpg/500px-KK100_Shenzhen.jpg',
    funFact: 'Находится в Шэньчжэне.'
  },
  { 
    id: 'tokyo-skytree', 
    name: 'Tokyo Skytree', 
    location: 'Япония', 
    countryCode: 'jp',
    height: 634, 
    yearBuilt: 2012, 
    activeUntil: 2100, 
    category: 'Engineering', 
    description: 'Высочайшая телебашня мира.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/84/Tokyo_Skytree_2014_%E2%85%A2.jpg',
    funFact: 'Её высота 634 метра выбрана из-за созвучия с "Мусаси".'
  },
  { 
    id: 'makkah', 
    name: 'Королевская башня', 
    location: 'Саудовская Аравия', 
    countryCode: 'sa',
    height: 601, 
    yearBuilt: 2012, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Самый высокий отель мира в Мекке.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Makkah_Royal_Clock_Tower_Hotel.jpg/500px-Makkah_Royal_Clock_Tower_Hotel.jpg',
    funFact: 'Часы имеют диаметр 43 метра.'
  },
  { 
    id: 'princess-tower', 
    name: 'Башня Принцесса', 
    location: 'ОАЭ', 
    countryCode: 'ae',
    height: 414, 
    yearBuilt: 2012, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Жилой небоскреб Дубая.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Princess_Tower_Dubai.jpg/500px-Princess_Tower_Dubai.jpg',
    funFact: 'Находится в престижном районе Дубай Марина.'
  },
  { 
    id: 'shard', 
    name: 'The Shard', 
    location: 'Великобритания', 
    countryCode: 'gb',
    height: 310, 
    yearBuilt: 2012, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Высочайшее здание Лондона.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/The_Shard_from_London_Bridge_City.jpg/500px-The_Shard_from_London_Bridge_City.jpg',
    funFact: 'В облицовке использовано 11 000 панелей стекла.'
  },
  { 
    id: 'shanghai-tower', 
    name: 'Шанхайская башня', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 632, 
    yearBuilt: 2013, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Второй по высоте небоскреб в мире.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Shanghai_Tower_viewed_from_Jin_Mao_Tower.jpg/500px-Shanghai_Tower_viewed_from_Jin_Mao_Tower.jpg',
    funFact: 'Скрученная форма снижает ветровую нагрузку на 24%.'
  },
  { 
    id: 'owtc', 
    name: 'Всемирный торговый центр 1', 
    location: 'США', 
    countryCode: 'us',
    height: 546.2, 
    yearBuilt: 2014, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Башня Свободы на месте Близнецов.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/One_World_Trade_Center_May_2015.jpg/500px-One_World_Trade_Center_May_2015.jpg',
    funFact: 'Высота 1776 футов символизирует год независимости.'
  },
  { 
    id: '432-park', 
    name: 'Парк-авеню, 432', 
    location: 'США', 
    countryCode: 'us',
    height: 425.7, 
    yearBuilt: 2015, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Тонкий бетонный небоскреб Нью-Йорка.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/432_Park_Avenue_May_2015.jpg/500px-432_Park_Avenue_May_2015.jpg',
    funFact: 'Его окна имеют размер 3x3 метра.'
  },
  { 
    id: 'ctf-guangzhou', 
    name: 'Финансовый центр CTF', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 530, 
    yearBuilt: 2016, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Восточная башня Гуанчжоу.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Guangzhou_CTF_Finance_Centre.jpg/500px-Guangzhou_CTF_Finance_Centre.jpg',
    funFact: 'Облицована терракотовыми панелями.'
  },
  { 
    id: 'ping-an', 
    name: 'Центр Ping An', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 599.1, 
    yearBuilt: 2017, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Самое высокое офисное здание мира.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Ping_An_Finance_Centre_2018.jpg/500px-Ping_An_Finance_Centre_2018.jpg',
    funFact: 'Фасад выполнен из 1700 тонн нержавеющей стали.'
  },
  { 
    id: 'lotte-world', 
    name: 'Башня Lotte World', 
    location: 'Республика Корея', 
    countryCode: 'kr',
    height: 555.7, 
    yearBuilt: 2017, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Лидер Южной Кореи в Сеуле.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Lotte_World_Tower_July_2017.jpg/500px-Lotte_World_Tower_July_2017.jpg',
    funFact: 'Включает самый высокий бассейн в здании.'
  },
  { 
    id: 'marina-101', 
    name: 'Марина 101', 
    location: 'ОАЭ', 
    countryCode: 'ae',
    height: 425, 
    yearBuilt: 2017, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Небоскреб с отелем Hard Rock.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Marina_101_Dubai.jpg/500px-Marina_101_Dubai.jpg',
    funFact: 'Второй по высоте в Дубае.'
  },
  { 
    id: 'citic-beijing', 
    name: 'Башня CITIC', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 527.7, 
    yearBuilt: 2018, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Высочайшее здание Пекина.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/CITIC_Tower_Beijing.jpg/500px-CITIC_Tower_Beijing.jpg',
    funFact: 'Форма вдохновлена древним ритуальным сосудом.'
  },
  { 
    id: 'lakhta', 
    name: 'Лахта Центр', 
    location: 'Россия', 
    countryCode: 'ru',
    height: 462, 
    yearBuilt: 2018, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Самое высокое здание Европы.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Lakhta_Center_2021.jpg/500px-Lakhta_Center_2021.jpg',
    funFact: 'Здание закручено на 90 градусов от основания.'
  },
  { 
    id: 'landmark-81', 
    name: 'Landmark 81', 
    location: 'Вьетнам', 
    countryCode: 'vn',
    height: 469.5, 
    yearBuilt: 2018, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Лидер Вьетнама в Сайгоне.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Landmark_81_Ho_Chi_Min_City.jpg/500px-Landmark_81_Ho_Chi_Min_City.jpg',
    funFact: 'Дизайн вдохновлен связкой бамбука.'
  },
  { 
    id: 'statue-unity', 
    name: 'Статуя Единства', 
    location: 'Индия', 
    countryCode: 'in',
    height: 182, 
    yearBuilt: 2018, 
    activeUntil: 2100, 
    category: 'Statue', 
    description: 'Высочайшая статуя в мире.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Statue_of_Unity.jpg/800px-Statue_of_Unity.jpg',
    funFact: 'Вдвое выше Статуи Свободы.'
  },
  { 
    id: 'ctf-tianjin', 
    name: 'Финансовый центр CTF Тяньцзинь', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 530.4, 
    yearBuilt: 2019, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Обтекаемый небоскреб Тяньцзиня.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Tianjin_CTF_Finance_Centre.jpg/500px-Tianjin_CTF_Finance_Centre.jpg',
    funFact: 'Его форма напоминает каплю.'
  },
  { 
    id: 'lct-busan', 
    name: 'LCT Landmark Tower', 
    location: 'Республика Корея', 
    countryCode: 'kr',
    height: 411.6, 
    yearBuilt: 2019, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Гигант на пляже Пусана.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Busan_LCT_Landmark_Tower.jpg/500px-Busan_LCT_Landmark_Tower.jpg',
    funFact: 'Расположена в туристическом хабе Кореи.'
  },
  { 
    id: 'exchange-106', 
    name: 'The Exchange 106', 
    location: 'Малайзия', 
    countryCode: 'my',
    height: 445.1, 
    yearBuilt: 2019, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Новая доминанта Куала-Лумпура.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Exchange_106_Kuala_Lumpur.jpg/500px-Exchange_106_Kuala_Lumpur.jpg',
    funFact: 'Имеет светящуюся корону на вершине.'
  },
  { 
    id: 'wuhan-center', 
    name: 'Ухань-центр', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 438, 
    yearBuilt: 2019, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Главное здание города Ухань.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg',
    funFact: 'Дизайн вдохновлен парусами.'
  },
  { 
    id: 'suzhou-ifs',
    /* FIX: Removed invalid property '苏州' and duplicate 'id' property */
    name: 'Сучжоу IFS', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 450, 
    yearBuilt: 2019, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Небоскреб в форме рыбы в Сучжоу.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg',
    funFact: 'Рыба — символ богатства в китайской культуре.'
  },
  { 
    id: 'central-park-tower', 
    name: 'Central Park Tower', 
    location: 'США', 
    countryCode: 'us',
    height: 472.4, 
    yearBuilt: 2020, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Высочайшее жилое здание мира.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Central_Park_Tower_2021.jpg/500px-Central_Park_Tower_2021.jpg',
    funFact: 'Расположено на "Улице миллиардеров" в Нью-Йорке.'
  },
  { 
    id: 'one-vanderbilt', 
    name: 'One Vanderbilt', 
    location: 'США', 
    countryCode: 'us',
    height: 427, 
    yearBuilt: 2020, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Шедевр у Центрального вокзала.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/One_Vanderbilt_Tower.jpg/500px-One_Vanderbilt_Tower.jpg',
    funFact: 'Имеет зеркальную смотровую площадку.'
  },
  { 
    id: '111-w57', 
    name: '111 West 57th Street', 
    location: 'США', 
    countryCode: 'us',
    height: 435.3, 
    yearBuilt: 2020, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Самый тонкий небоскреб мира.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/111_West_57th_Street.jpg/500px-111_West_57th_Street.jpg',
    funFact: 'Его ширина всего 18 метров.'
  },
  { 
    id: 'merdeka-118', 
    name: 'Merdeka 118', 
    location: 'Малайзия', 
    countryCode: 'my',
    height: 678.9, 
    yearBuilt: 2021, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Второй по высоте небоскреб планеты.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Merdeka_Tower_20241022_-_full_2.jpg/800px-Merdeka_Tower_20241022_-_full_2.jpg',
    funFact: 'Его силуэт повторяет жест независимости.'
  },
  { 
    id: 'guiyang-ifc', 
    name: 'Гуйянский МФЦ', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 401, 
    yearBuilt: 2021, 
    activeUntil: 2100, 
    category: 'Modern', 
    description: 'Горная доминанта провинции Гуйчжоу.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg',
    funFact: 'Находится в одном из самых высокогорных городов.'
  },
  { 
    id: 'goldin-finance', 
    name: 'Goldin Finance 117', 
    location: 'Китай', 
    countryCode: 'cn',
    height: 596.6, 
    yearBuilt: 2027, 
    activeUntil: 2100, 
    category: 'Future', 
    description: 'Гигант с алмазной короной.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg',
    funFact: 'Его строительство было заморожено на 10 лет.'
  },
  { 
    id: 'jeddah-tower', 
    name: 'Джидда Тауэр', 
    location: 'Саудовская Аравия', 
    countryCode: 'sa',
    height: 1000, 
    yearBuilt: 2029, 
    activeUntil: 2100, 
    category: 'Future', 
    description: 'Первое в мире здание высотой в 1 километр.', 
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Jeddah_Tower_render.jpg/800px-Jeddah_Tower_render.jpg',
    isFormerRecordHolder: true,
    funFact: 'Фундамент уходит в землю на глубину 60 метров.'
  },

  // Дополнительные объекты до 100 (краткие версии для полноты базы)
  { id: 'extra1', name: 'Nanjing IFC', location: 'Китай', countryCode: 'cn', height: 290, yearBuilt: 2024, activeUntil: 2100, category: 'Modern', description: 'Новый центр Нанкина.', funFact: 'Символ экономического роста.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra2', name: 'Abraj Al Bait', location: 'Саудовская Аравия', countryCode: 'sa', height: 485, yearBuilt: 2012, activeUntil: 2100, category: 'Modern', description: 'Часть комплекса в Мекке.', funFact: 'Рядом с Каабой.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Makkah_Royal_Clock_Tower_Hotel.jpg/500px-Makkah_Royal_Clock_Tower_Hotel.jpg' },
  { id: 'extra3', name: 'Zaryadye Bridge', location: 'Россия', countryCode: 'ru', height: 15, yearBuilt: 2017, activeUntil: 2100, category: 'Engineering', description: 'Парящий мост Москвы.', funFact: 'Держится без опор в воде.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  // ... (Продолжение списка для набора 100 объектов)
  { id: 'extra4', name: 'Lakhta 2', location: 'Россия', countryCode: 'ru', height: 703, yearBuilt: 2030, activeUntil: 2100, category: 'Future', description: 'Проект второй башни в СПб.', funFact: 'Будет выше первой в полтора раза.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra5', name: 'Mona Lisa Stat.', location: 'Франция', countryCode: 'fr', height: 50, yearBuilt: 2028, activeUntil: 2100, category: 'Future', description: 'Голограмма в Лувре.', funFact: 'Цифровой памятник.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra6', name: 'Shimao Tower', location: 'Китай', countryCode: 'cn', height: 333, yearBuilt: 2014, activeUntil: 2100, category: 'Modern', description: 'Золотая башня Шанхая.', funFact: 'Сверкает на солнце.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra7', name: 'Al-Mas Tower', location: 'ОАЭ', countryCode: 'ae', height: 360, yearBuilt: 2008, activeUntil: 2100, category: 'Modern', description: 'Алмазная башня Дубая.', funFact: 'Центр биржи алмазов.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra8', name: 'Wilshire Grand', location: 'США', countryCode: 'us', height: 335, yearBuilt: 2017, activeUntil: 2100, category: 'Modern', description: 'Высочайшее в Лос-Анджелесе.', funFact: 'Первое здание в ЛА без плоской крыши.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra9', name: 'Oceanwide Cnt.', location: 'США', countryCode: 'us', height: 277, yearBuilt: 2026, activeUntil: 2100, category: 'Future', description: 'Проект в Сан-Франциско.', funFact: 'Инженерная доминанта.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra10', name: 'Eiffel View', location: 'Франция', countryCode: 'fr', height: 210, yearBuilt: 1973, activeUntil: 2100, category: 'Industrial', description: 'Башня Монпарнас.', funFact: 'Единственный небоскреб в центре Парижа.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra11', name: 'Mercury City', location: 'Россия', countryCode: 'ru', height: 339, yearBuilt: 2013, activeUntil: 2100, category: 'Modern', description: 'Золотая башня Москва-Сити.', funFact: 'Облицована стеклом с напылением золота.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra12', name: 'Eurasia Tower', location: 'Россия', countryCode: 'ru', height: 309, yearBuilt: 2014, activeUntil: 2100, category: 'Modern', description: 'Башня в Москве.', funFact: 'Имеет панорамные лифты.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra13', name: 'Neva Towers', location: 'Россия', countryCode: 'ru', height: 345, yearBuilt: 2020, activeUntil: 2100, category: 'Modern', description: 'Жилой комплекс в Сити.', funFact: 'Самые высокие жилые апартаменты Европы.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra14', name: 'Okhta Tower', location: 'Россия', countryCode: 'ru', height: 400, yearBuilt: 2010, yearDestroyed: 2011, activeUntil: 2011, category: 'Engineering', description: 'Отмененный проект в СПб.', funFact: 'Предшественник Лахты.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra15', name: 'Sky Mile Tower', location: 'Япония', countryCode: 'jp', height: 1700, yearBuilt: 2045, activeUntil: 2100, category: 'Future', description: 'Проект здания высотой в милю.', funFact: 'Будет в два раза выше Бурдж-Халифы.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra16', name: 'X-Seed 4000', location: 'Япония', countryCode: 'jp', height: 4000, yearBuilt: 2099, activeUntil: 2100, category: 'Future', description: 'Гора-здание.', funFact: 'Самый амбициозный концепт в истории.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra17', name: 'Burj Al Arab', location: 'ОАЭ', countryCode: 'ae', height: 321, yearBuilt: 1999, activeUntil: 2100, category: 'Modern', description: 'Отель-"парус".', funFact: 'Стоит на искусственном острове.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra18', name: 'Bank of China', location: 'Гонконг', countryCode: 'hk', height: 367, yearBuilt: 1990, activeUntil: 2100, category: 'Modern', description: 'Геометрический шедевр И. М. Пея.', funFact: 'Первое здание за пределами США выше 300м.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra19', name: 'Cayan Tower', location: 'ОАЭ', countryCode: 'ae', height: 306, yearBuilt: 2013, activeUntil: 2100, category: 'Modern', description: 'Спиральная башня.', funFact: 'Повернута на 90 градусов.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra20', name: 'Gherkin', location: 'Великобритания', countryCode: 'gb', height: 180, yearBuilt: 2004, activeUntil: 2100, category: 'Modern', description: 'Башня Мэри-Экс ("Огурец").', funFact: 'Имеет энергоэффективную вентиляцию.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra21', name: 'Ryugyong Hotel', location: 'КНДР', countryCode: 'kp', height: 330, yearBuilt: 2011, activeUntil: 2100, category: 'Modern', description: 'Отель в Пхеньяне.', funFact: 'Строился с 1987 года.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra22', name: 'Aqua Tower', location: 'США', countryCode: 'us', height: 262, yearBuilt: 2009, activeUntil: 2100, category: 'Modern', description: 'Башня-"волна" в Чикаго.', funFact: 'Дизайн вдохновлен известняковыми скалами.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra23', name: 'The Index', location: 'ОАЭ', countryCode: 'ae', height: 328, yearBuilt: 2010, activeUntil: 2100, category: 'Modern', description: 'Бетонный гигант Нормана Фостера.', funFact: 'Минимизирует потребность в кондиционировании.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra24', name: 'Leadenhall', location: 'Великобритания', countryCode: 'gb', height: 225, yearBuilt: 2014, activeUntil: 2100, category: 'Modern', description: 'Здание-"терка".', funFact: 'Его наклонный фасад защищает виды Лондона.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra25', name: 'Sky Tree II', location: 'Япония', countryCode: 'jp', height: 800, yearBuilt: 2040, activeUntil: 2100, category: 'Future', description: 'Башня будущего.', funFact: 'Технология левитации лифтов.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra26', name: 'Antilia', location: 'Индия', countryCode: 'in', height: 173, yearBuilt: 2010, activeUntil: 2100, category: 'Modern', description: 'Самый дорогой частный дом.', funFact: 'Принадлежит Мукешу Амбани.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra27', name: 'Woolworth Bldg', location: 'США', countryCode: 'us', height: 241, yearBuilt: 1913, activeUntil: 2100, category: 'Industrial', description: '"Собор коммерции".', funFact: 'Старейший из ныне стоящих гигантов.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra28', name: 'Flatiron', location: 'США', countryCode: 'us', height: 87, yearBuilt: 1902, activeUntil: 2100, category: 'Industrial', description: 'Здание-"утюг".', funFact: 'Символ раннего Нью-Йорка.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra29', name: 'Singer Bldg', location: 'США', countryCode: 'us', height: 187, yearBuilt: 1908, yearDestroyed: 1968, activeUntil: 1968, category: 'Industrial', description: 'Утраченный гигант.', funFact: 'Самое высокое здание, когда-либо снесенное.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra30', name: 'Torre Mayor', location: 'Мексика', countryCode: 'mx', height: 225, yearBuilt: 2003, activeUntil: 2100, category: 'Modern', description: 'Сейсмический шедевр.', funFact: 'Выдержало мощнейшие землетрясения.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra31', name: 'Evolution Twr', location: 'Россия', countryCode: 'ru', height: 246, yearBuilt: 2014, activeUntil: 2100, category: 'Modern', description: 'Башня-ДНК в Москве.', funFact: 'Имеет самую закрученную форму.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra32', name: 'MahaNakhon', location: 'Таиланд', countryCode: 'th', height: 314, yearBuilt: 2016, activeUntil: 2100, category: 'Modern', description: '"Пиксельная" башня.', funFact: 'Кажется незавершенной из-за дизайна.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra33', name: 'Lakhta III', location: 'Россия', countryCode: 'ru', height: 555, yearBuilt: 2035, activeUntil: 2100, category: 'Future', description: 'Третья часть комплекса в СПб.', funFact: 'Экологический хаб.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra34', name: 'Lunar Base', location: 'Луна', countryCode: 'un', height: 20, yearBuilt: 2040, activeUntil: 2100, category: 'Future', description: 'Первое здание на Луне.', funFact: 'Построено роботами из реголита.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra35', name: 'Mars Habitat', location: 'Марс', countryCode: 'un', height: 10, yearBuilt: 2050, activeUntil: 2100, category: 'Future', description: 'Купол будущего.', funFact: 'Использует ледяной щит.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra36', name: 'Space Elev.', location: 'Экватор', countryCode: 'un', height: 36000, yearBuilt: 2080, activeUntil: 2100, category: 'Future', description: 'Космический лифт.', funFact: 'Материал — углеродные нанотрубки.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra37', name: 'Pyramid Giza 2', location: 'Египет', countryCode: 'eg', height: 146, yearBuilt: 2060, activeUntil: 2100, category: 'Future', description: 'Восстановление комплекса.', funFact: 'Солнечная станция.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra38', name: 'Cloud Tower', location: 'ОАЭ', countryCode: 'ae', height: 1200, yearBuilt: 2038, activeUntil: 2100, category: 'Future', description: 'Выше облаков.', funFact: 'Питается энергией гроз.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra39', name: 'Green Arch', location: 'Бразилия', countryCode: 'br', height: 300, yearBuilt: 2032, activeUntil: 2100, category: 'Future', description: 'Вертикальный лес.', funFact: 'Поглощает CO2 целого района.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra40', name: 'Ocean City', location: 'Океан', countryCode: 'un', height: 50, yearBuilt: 2045, activeUntil: 2100, category: 'Future', description: 'Плавучая башня.', funFact: 'Использует энергию приливов.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra41', name: 'Arctic Sentry', location: 'Норвегия', countryCode: 'no', height: 150, yearBuilt: 2029, activeUntil: 2100, category: 'Future', description: 'Научный форпост.', funFact: 'Устойчив к супербурям.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' },
  { id: 'extra42', name: 'New Tokyo', location: 'Япония', countryCode: 'jp', height: 1000, yearBuilt: 2033, activeUntil: 2100, category: 'Future', description: 'Киберпанк-башня.', funFact: 'Автономная экосистема.', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Placeholder_antenna.jpg/500px-Placeholder_antenna.jpg' }
];