import fs from 'fs';
let content = fs.readFileSync('data.ts', 'utf8');

const replacements: Record<string, string> = {
  'China Zun (CITIC Tower)': 'Чайна-Цзунь',
  'Wuhan Greenland Center': 'Гринлэнд-центр (Ухань)',
  'Changsha IFS Tower T1': 'Чанша IFS',
  'Suzhou IFS': 'Сучжоу IFS',
  'KK100': 'КК100',
  'Guangzhou International Finance Center': 'Международный финансовый центр (Гуанчжоу)',
  'Steinway Tower': 'Стейнвей-тауэр',
  'One Vanderbilt': 'Уан-Вандербильт',
  'Marina 101': 'Марина 101',
  'Trump International Hotel and Tower': 'Международный отель и башня Трампа',
  'Princess Tower': 'Башня Принцессы',
  'Al Hamra Tower': 'Аль-Хамра',
  'Two International Finance Centre': 'Международный финансовый центр (Гонконг)',
  'Nanning China Resources Tower': 'Башня China Resources (Наньнин)',
  'Guiyang International Financial Center T1': 'Международный финансовый центр (Гуйян)',
  'China Resources Headquarters': 'Штаб-квартира China Resources',
  '23 Marina': '23 Марина',
  'CITIC Plaza': 'Ситик-плаза',
  'Shum Yip Upperhills Tower 1': 'Shum Yip Upperhills',
  '30 Hudson Yards': 'Хадсон-Ярдс, 30',
  'Capital Market Authority Headquarters': 'Штаб-квартира Capital Market Authority',
  'Shun Hing Square': 'Сёньхин-сквер',
  'Autograph Tower': 'Башня Автограф',
  'Riverview Plaza': 'Ривервью-плаза',
  'Shenzhen Center': 'Шэньчжэнь-центр',
  'Central Plaza': 'Сентрал-плаза',
  'Dalian International Trade Center': 'Даляньский международный торговый центр',
  'Address Boulevard': 'Адрес Бульвар',
  'Golden Eagle Tiandi Tower A': 'Golden Eagle Tiandi',
  'Bank of China Tower': 'Башня Банка Китая',
  'Bank of America Tower': 'Башня Банка Америки',
  'Almas Tower': 'Алмазная башня',
  'Gevora Hotel': 'Отель Гевора',
  'Il Primo Tower': 'Башня Ил Примо',
  'SEG Plaza': 'СЭГ Плаза',
  'Emirates Office Tower': 'Эмирейтс Офис Тауэр',
  'Raffles City Chongqing T3N': 'Раффлз-Сити (Чунцин) T3N',
  'Raffles City Chongqing T4N': 'Раффлз-Сити (Чунцин) T4N',
  'The Pinnacle': 'Зе Пиннакл',
  '85 Sky Tower': '85 Скай Тауэр',
  'Aon Center': 'Аон-центр',
  'The Center': 'Центр (Гонконг)',
  'John Hancock Center': 'Джон Хэнкок Центр',
  'Shimao Global Financial Center': 'Shimao Global Financial Center',
  'ADNOC Headquarters': 'Штаб-квартира ADNOC',
  'One Shenzhen Bay': 'Уан Шэньчжэнь Бэй',
  'Wuxi International Finance Square': 'Международная финансовая площадь Уси',
  'Chongqing World Financial Center': 'Всемирный финансовый центр Чунцина',
  'Tianjin Modern City Office Tower': 'Офисная башня современного города Тяньцзиня',
  'Suning Plaza': 'Сунин Плаза',
  'Hengqin International Finance Center': 'Хэнциньский международный финансовый центр',
  'DAMAC Residenze': 'ДАМАК Резиденс',
  'Twin Towers Macau': 'Двойные башни Макао',
  'Shimao International Plaza': 'Шимао Интернэшнл Плаза',
  'Rose Rayhaan by Rotana': 'Роуз-Райхаан (Rotana)',
  'Jinan Centre Financial City': 'Финансовый город (Цзинань)',
  'Minsheng Bank Building': 'Здание банка Миншэн',
  'China World Trade Center Tower III': 'Китайский всемирный торговый центр (Башня 3)',
  'Zhuhai St. Regis Hotel & Office Tower': 'Отель St. Regis (Чжухай)',
  'Hon Kwok City Center': 'Хон-Квок Сити-Центр',
  'Keangnam Hanoi Landmark Tower': 'Кеннам Ханой Лендмарк Тауэр',
  'Three World Trade Center': 'Всемирный торговый центр 3',
  'Baoneng Center': 'Баонэн-центр',
  'Wuxi Suning Plaza 1': 'Уси Сунин Плаза',
  'Al Yaqoub Tower': 'Башня Аль-Якуб',
  'The Index': 'Индекс (небоскрёб)',
  'The Landmark': 'Башня Лендмарк',
  'Deji Plaza': 'Дэцзи-Плаза',
  'Yantai Shimao No.1 The Harbour': 'Шимао Харбор (Яньтай)',
  'Q1 Tower': 'Башня Q1',
  'Wenzhou World Trade Center': 'Всемирный торговый центр Вэньчжоу',
  'Nina Tower': 'Башня Нина',
  'Sinar Mas Center 1': 'Синар Мас Центр',
  'Global City Square': 'Глобал Сити Сквер',
  'New York Times Building': 'Нью-Йорк Таймс-билдинг',
  'Chongqing IFS T1': 'Чунцин IFS',
  'Honglou Times Square': 'Хунлоу Таймс-сквер',
  'MahaNakhon': 'Маханакон',
  'Bank of America Plaza': 'Банк оф Америка Плаза',
  'Moynihan Train Hall': 'Мойнихан Трейн Холл',
  'Ocean Heights': 'Оушен Хайтс',
  'Varso Tower': 'Варсо',
  'Pearl River Tower': 'Башня Жемчужной реки',
  'Fortune Center': 'Форчун-центр',
  'Jumeirah Emirates Towers Hotel': 'Джумейра Эмирейтс Тауэрс',
  'Starlight Place': 'Старлайт-Плейс',
  'Guangfa Securities Headquarters': 'Штаб-квартира Guangfa Securities',
  'Burj Rafal': 'Бурдж-Рафаль',
  '35 Hudson Yards': 'Хадсон-Ярдс, 35',
  'Wanda Plaza': 'Ванда Плаза',
  'Amoco Building': 'Амоко-билдинг',
  'Cayan Tower': 'Башня Кайан',
  'East Pacific Center Tower A': 'Восточно-Тихоокеанский центр (Башня А)',
  'The Address Downtown Dubai': 'Адрес Даунтаун Дубай',
  'Kingdom Centre': 'Бурдж Аль-Мамляка',
  'Huaguoyuan Tower 1': 'Башня Хуагоюань 1',
  'Huaguoyuan Tower 2': 'Башня Хуагоюань 2',
  'Gran Torre Santiago': 'Гран Торре Сантьяго',
  'Abeno Harukas': 'Абэно Харукас',
  'NBK Tower': 'Башня NBK',
  'First Canadian Place': 'Фёст-Канейдиан-Плэйс',
  'Shanghai Wheelock Square': 'Уилок-сквер',
  '4 World Trade Center': 'Всемирный торговый центр 4',
  'Comcast Center': 'Комкаст-центр',
  'Eureka Tower': 'Башня Эврика',
  'Landmark 72': 'Лендмарк 72',
  'OUE Downtown 1': 'ОУЭ Даунтаун 1',
  '311 South Wacker Drive': 'Саут-Уокер-драйв, 311',
  'Global Trade Center': 'Глобал Трейд Центр',
  '70 Pine Street': 'Пайн-стрит, 70',
  'Key Tower': 'Ки-Тауэр',
  'One Liberty Place': 'Уан-Либерти-Плейс',
  'Columbia Center': 'Колумбия-центр',
  'The Address Dubai Mall': 'Адрес Дубай Молл',
  '22 Bishopsgate': '22 Бишопсгейт',
  'Citigroup Center': 'Ситигрупп-центр',
  'Scotia Plaza': 'Скошия-Плаза',
  'Williams Tower': 'Уильямс-Тауэр',
};

// Also apply some manual replacements for the objects in EXPORT CONST BUILDINGS
const buildingReplacements: Record<string, string> = {
  'China Zun (CITIC Tower)': 'Чайна-Цзунь',
  'Wuhan Greenland Center': 'Гринлэнд-центр (Ухань)',
  'Changsha IFS Tower T1': 'Чанша IFS',
  'Suzhou IFS': 'Сучжоу IFS',
  'Guangzhou International Finance Center': 'Международный финансовый центр (Гуанчжоу)',
  'Two International Finance Centre': 'Международный финансовый центр (Гонконг)',
  'Trump International Hotel and Tower': 'Международный отель и башня Трампа',
  'LCT The Sharp Landmark Tower': 'Haeundae LCT The Sharp',
  'Steinway Tower': 'Стейнвей-тауэр',
  'One Vanderbilt': 'Уан-Вандербильт'
};

for (const [en, ru] of Object.entries(replacements)) {
  const regex = new RegExp(`name: '${en}'`, 'g');
  content = content.replace(regex, `name: '${ru}'`);
}

for (const [en, ru] of Object.entries(buildingReplacements)) {
  const regex2 = new RegExp(`name: '${en}'`, 'g');
  content = content.replace(regex2, `name: '${ru}'`);
}

fs.writeFileSync('data.ts', content);
console.log('Replacements complete');
